### ISSUE TITLE
The update in DQN

### ISSUE THREAD

**Issue by YuxuanXie** [higgsfield/RL-Adventure#31]
Hi,

I get a question about your implementation of DQN, which is supposed to have a C-interval-update between target q-network and current q-network.  I see this update in your implementation of DDQN. Can you please tell me why it is this way?

In my point of view, your implementation of ddqn is actually dqn.

------
Best,
Yuxuan

**Comment by douglasrizzo** [comment]
I realized that too. In fact, there is no target network at all in [1.dqn.ipynb](https://github.com/higgsfield/RL-Adventure/blob/47e337d9b9513ec1ae777d7f0a357e8f42902676/1.dqn.ipynb).

The following line in the notebook (cell 19):

```python
next_q_values = model(next_state)
```

Should be:

```python
next_q_values = target_model(next_state)
```

**Comment by YuxuanXie** [comment]
Yes, you are right. thanks!
