### ISSUE TITLE
Any possibilities to include A3C implementation?

### ISSUE THREAD

**Issue by hohoCode** [higgsfield/RL-Adventure#4]
Thank you for your great tutorial.

**Comment by higgsfield** [comment]
Thanks! Actor-Critic will be in RL-adventure-2 :)

**Comment by hohoCode** [comment]
Thanks! 

I am also sure you have noticed this very recent work: ['Distributed Prioritized Experience Replay'](https://arxiv.org/pdf/1803.00933.pdf), which pushed everything to a whole new level (beating Rainbow a lot...). I know [RayLIB](https://github.com/ray-project/ray/blob/master/python/ray/rllib/dqn/apex.py) has implemented a basic APEX framework to do so, probably just need to connect the dots. If this work can be included in your great tutorial that would be amazing. Thanks.
